{
 "title": "Soal Undi Dashboard",
 "time": { "from": "2022-11-29T00:00:00.000Z", "to": "2022-12-27T00:00:00.000Z" },
 "panels": [
  { "title": "Usage Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Usage Map",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 10, "x": 1, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \"Latitude\", \"Longitude\", \"Timestamp\" FROM \"Geolocation\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Questions\") FROM \"Questions\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Daily Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Questions\") FROM \"Questions\" WHERE \"Timestamp\" = CURRENT_DATE LIMIT 50 "
    }
   ]
  },
  {
   "title": "Weekly Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Questions\") FROM \"Questions\" WHERE \"Timestamp\" BETWEEN date_trunc('week', current_date) AND date_trunc('week', current_date) + interval '1 week'"
    }
   ]
  },
  {
   "title": "Monthly Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Questions\") FROM \"Questions\" WHERE \"Timestamp\" BETWEEN date_trunc('month', current_date) AND date_trunc('month', current_date) + interval '1 month'"
    }
   ]
  },
  {
   "title": "Usage (messages) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Questions\"), \"Timestamp\" FROM \"Questions\" GROUP BY \"Timestamp\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Unique users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Timestamp\") FROM \"Geolocation\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Satisfaction rate",
   "type": "nikosc-percenttrend-panel",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Response\") AS \"Feedback\" FROM \"Satisfaction\" WHERE \"Response\" = 'Yes';"
    },
    {
     "rawSql": "SELECT COUNT(\"Response\") AS \"Negative\" FROM \"Satisfaction\" WHERE \"Response\" = 'No';"
    }
   ]
  },
  {
   "title": "Avg. response Time (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"Response_time\") FROM \"Questions\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Missed messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Question\") FROM \"Missed\" LIMIT 50 "
    }
   ]
  },
  { "title": "Text Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Question Log",
   "type": "logs",
   "gridPos": { "h": 28, "w": 5, "x": 1, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \"Timestamp\", \"Questions\" FROM \"Questions\" ORDER BY \"Timestamp\" DESC "
    }
   ]
  },
  {
   "title": "Missed messages",
   "type": "table",
   "gridPos": { "h": 28, "w": 5, "x": 6, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \"Timestamp\", \"Question\" FROM \"Missed\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Freq. Keywords",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"Frequency\") FROM \"Keywords\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total No. of Keywords",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"Keywords\") FROM \"Keywords\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Freq. of Keywords",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"Frequency\") FROM \"Keywords\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Most Freq. Keyword",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(\"Frequency\") FROM \"Keywords\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Keyword Histogram",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \"Frequency\", \"Keywords\" FROM \"Keywords\" WHERE \"Frequency\" > 1  "
    }
   ]
  },
  {
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 14, "w": 6, "x": 11, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT \"Keywords\", \"Frequency\" FROM \"Keywords\" WHERE \"Frequency\" > 1 LIMIT 50 "
    }
   ]
  },
  {
   "title": "Keywords Breakdown (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 6, "x": 17, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT \"Keywords\", \"Frequency\" FROM \"Keywords\" ORDER BY \"Frequency\" DESC LIMIT 10"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } }
 ]
}